Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
labels_t5 = y_pred > .5
print("Proportion classified as spam: {x}".format(x = round(labels_t5.mean(), 4)))
print("Proportion actual spam: {x}".format(x = round(df_spam['spam'].mean(), 4)))
print("Accuracy: {x}".format(x = round(accuracy_score(labels_t5, df_spam['spam']), 2)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [11][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mProportion classified as spam: [39m[38;5;132;01m{x}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(x [38;5;241m=[39m [38;5;28mround[39m(labels_t5[38;5;241m.[39mmean(), [38;5;241m4[39m)))
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mProportion actual spam: [39m[38;5;132;01m{x}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(x [38;5;241m=[39m [38;5;28mround[39m(df_spam[[38;5;124m'[39m[38;5;124mspam[39m[38;5;124m'[39m][38;5;241m.[39mmean(), [38;5;241m4[39m)))
[0;32m----> 4[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mAccuracy: [39m[38;5;132;01m{x}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(x [38;5;241m=[39m [38;5;28mround[39m([43maccuracy_score[49m(labels_t5, df_spam[[38;5;124m'[39m[38;5;124mspam[39m[38;5;124m'[39m]), [38;5;241m2[39m)))

[0;31mNameError[0m: name 'accuracy_score' is not defined
NameError: name 'accuracy_score' is not defined

